version: "3.8"

services:
  next-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
